services:
  lora_pilot_dev:
    image: lora_pilot-dev:1.0
    platform: linux/amd64
    build:
      context: .
      # in case of missing .env file (eg. CI/CD) system will use default values
      args:
        GID_NUMBER: ${GID_NUMBER:-1000}
        UID_NUMBER: ${UID_NUMBER:-1000}
        DOCKER_IMAGE_ROOT: ${DOCKER_IMAGE_ROOT:-ubuntu:24.04}
        CONAN_LOGIN_USERNAME: ${CONAN_LOGIN_USERNAME:-""}
        CONAN_PASSWORD: ${CONAN_PASSWORD:-""}
    privileged: true
    group_add:
      - "4"
      - "20"
      - "24"
      - "25"
      - "27"
      - "29"
      - "30"
      - "44"
      - "46"
      - "100"
      - "114"
      - "124"
      - "984"
    volumes:
      - ..:/workspace
      - /dev:/dev
    command: sleep infinity
    ports:
      - "3333:3333"
      - "4444:4444"
      - "6666:6666"
